/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as helpers from "../helpers";
import type * as ingest_embed from "../ingest/embed";
import type * as ingest_load from "../ingest/load";
import type * as messages from "../messages";
import type * as serve from "../serve";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  helpers: typeof helpers;
  "ingest/embed": typeof ingest_embed;
  "ingest/load": typeof ingest_load;
  messages: typeof messages;
  serve: typeof serve;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
